<a href="https://colab.research.google.com/github/sohan1423/Ai-Assistant-using-python/blob/main/py_numpy_practice_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
np.array([1,3])

array([1, 3])

#Dimention

In [ ]:

arr = np.array([[[]]])
arr.ndim
arr.shape

(1, 1, 0)

In [ ]:
range = np.arange(1,10,2)  # start , stop, step
range

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.linspace(0,2,5)   #start, stop , num of value between start and stop
arr

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
arr = np.logspace(1,3,4)  #logarithomic ---10^1  to 10^3 ----between 4 points
arr

array([  10.        ,   46.41588834,  215.443469  , 1000.        ])

In [ ]:
arr = np.zeros(5)  # print num of zero in array which I want
arr

array([0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.ones([3,3])
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr = np.full([2,4],4)  #(dim [], value )
arr

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [ ]:
arr = np.random.rand(2,3) # create random value using dim --no need square baraket
arr

array([[0.95300221, 0.08864232, 0.98871817],
       [0.9535692 , 0.2401822 , 0.20793902]])

In [ ]:
arr = np.random.randn(2,3)  # also take neg value
arr

array([[ 1.53025397,  0.05277348,  0.71927435],
       [ 0.02592551, -0.39437879,  0.04930601]])

In [ ]:
arr = np.random.randint(10,89, (2,4)) # random int-------->basically range (start , stop) -----size means dim
arr

array([[35, 19, 33, 79],
       [49, 67, 87, 62]])

In [ ]:
arr = np.array([
                  [1,3,2],
                  [3,5,7],
                  [3,5,8]
                ])
print("Here the matrix")
print(arr)  # if I write print that erase the array write which wrote the sytem by default

Here the matrix
[[1 3 2]
 [3 5 7]
 [3 5 8]]


#data type and type casting

# we can't convert string to int or float its called casting error

In [ ]:
arr = np.array([1,3,3,4])
arr.dtype

dtype('int64')

In [ ]:
arr = np.array([1,3,3,4], dtype = np.float64)
arr.dtype

dtype('float64')

In [ ]:
# ----->type casting====> astype()

arr = np.array([1,3,4])
arr.dtype

dtype('int64')

In [ ]:
new_arr = arr.astype(np.float64)
new_arr

array([1., 3., 4.])

In [ ]:
new_arr.dtype

dtype('float64')

#Arary Re-shaping -------->Re-shape, Ravel, Flatten

In [ ]:


arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(2, 3)
reshaped



array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

r = arr.ravel()
print("Original:\n", arr)
print("Raveled:", r)

# Change element in ravel
r[0] = 99
print("After change, Original:\n", arr)


Original:
 [[1 2 3]
 [4 5 6]]
Raveled: [1 2 3 4 5 6]
After change, Original:
 [[99  2  3]
 [ 4  5  6]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

f = arr.flatten()
print("Flattened:", f)

# Change element in flatten
f[0] = 99
print("After change, Flattened:", f)
print("Original:\n", arr)


Flattened: [1 2 3 4 5 6]
After change, Flattened: [99  2  3  4  5  6]
Original:
 [[1 2 3]
 [4 5 6]]


#Arithmetic operation


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])


In [ ]:
print(a+b)

[5 7 9]


In [ ]:
print(a-b)

[-3 -3 -3]


In [ ]:
print(b-a)

[3 3 3]


In [ ]:
print(a/b) # // for int division

[0.25 0.4  0.5 ]


In [ ]:
print(a*b)

[ 4 10 18]


In [ ]:
# reminder
print(b%a)

[0 1 0]


In [ ]:
#exponent ->  power
print(a**b)

[  1  32 729]


# universal fuction -----> ufuncs


---



In [ ]:
arr = np.array([1,4,9,16])


In [ ]:
#square root -->n.sqrt()
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [ ]:
#exponential --> np.exp-->e^x
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [ ]:
#sine function

angles = np.array([0,np.pi/2,np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


#indexing and  scilicing

In [ ]:
# neg indexing
a = [1,2,3,4,5]


In [ ]:
a[-1:-4:  -1]  #last -1 help to print neg indexing otherwise print the empty set

[5, 4, 3]

In [ ]:
a[: : 2] # skip value

[1, 3, 5]

In [ ]:
#applied in numpy array
arr = np.array([1,2,3,4,5,6,7])
arr[ : : 2]

array([1, 3, 5, 7])

In [ ]:
# neg indexing
print(arr[-2])


6


#multi dim arry slicinf

In [ ]:
matrix =  np.array([
    [1,2,3],[4,5,6],[7,8,9]
])

In [ ]:
print(matrix[1:3 , 1:3])

[[5 6]
 [8 9]]


In [ ]:
#Advance indexing ---->Build in function to perfoem indexing and sclicing
arr = np.array([1,2,3,4,5,6,7])
a = [0,2]
print(np.take(arr,a))

[1 3]


#Iterating with nditer

In [ ]:
arr =([
    [1,2], [3,4]
])


In [ ]:
for x in np.nditer(arr):
  print(x, end = " ")

(array(1), array(3)) (array(2), array(4)) 

#views vs Copy

In [ ]:
arr = np.array([1,2,3,4,5,6])
view = arr[1:6]    # when we cnanges view is[3]----its range will effect

view


array([2, 3, 4, 5, 6])

In [ ]:
view[2] = 200

In [ ]:
arr

array([  1,   2,   3, 200,   5,   6])

In [ ]:
copy = arr[1:3].copy()
copy

array([2, 3])

#Transpose

In [ ]:
arr  = np.array([[1,3],[4,5]])
arr

array([[1, 3],
       [4, 5]])

In [ ]:
print(arr.transpose())

[[1 4]
 [3 5]]


#swapaxes--> swap 2 specific access

In [ ]:
arr = np.array([[[1,2],[3,4]]])
arr.shape

(1, 2, 2)

In [ ]:
swap = np.swapaxes(arr,0,1)
swap.shape

(2, 1, 2)

#concatenation

In [ ]:
a = np.array([2,4])
b = np.array([5,6])



In [ ]:
combine = np.concatenate((a,b))
combine

array([2, 4, 5, 6])

In [ ]:
# v starck -other way o omplement (vertical stack)
arr1  = np.array([[1,2], [3,4]])
arr2  = np.array([[5,6], [7,8]])


In [ ]:
print(np.vstack((arr1,arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#h stack-------(horizontal stack )
print(np.hstack((arr1,arr2)))


[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
print(np.stack((arr1,arr2), axis = 0))  #row wise

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
print(np.stack((arr1,arr2), axis = 1))    #  join coloumn wise

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [ ]:
#Repeating :
arr =  np.array([1,2,3])
print(np.repeat(arr,2))

[1 1 2 2 3 3]


In [ ]:
#tile----repeating whole array
print(np.tile(arr,3))

[1 2 3 1 2 3 1 2 3]


In [ ]:
#Aggregate function
arr = np.array([1,2,3])
print(np.sum(arr))

6


In [ ]:
np.mean(arr)

np.float64(2.0)

In [ ]:
np.median(arr)

np.float64(2.0)

In [ ]:
#standard division
np.std(arr)

np.float64(0.816496580927726)

In [ ]:
#variance
np.var(arr)

np.float64(0.6666666666666666)

In [ ]:
np.min(arr)

np.int64(1)

In [ ]:
np.max(arr)

np.int64(3)

In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#sum column wise or row wise
print(np.sum(matrix, axis = 0)) #row sum
print(np.sum(matrix, axis = 1)) #coloumn sum

[12 15 18]
[ 6 15 24]


In [ ]:
#cumulative operation -----> runing total
arr


array([1, 2, 3])

In [ ]:
print(np.cumsum(arr))

[1 3 6]


In [ ]:
print(np.cumprod(arr))# 1, 1*2=2, 1*2*3=6

[1 2 6]


In [ ]:
#where
arr

array([1, 2, 3])

In [ ]:
result = np.where(arr < 2, "low", "high")

In [ ]:
result

array(['low', 'high', 'high'], dtype='<U4')

In [ ]:
#logical and
arr = np.array([100,2,3,4,5,6])

In [ ]:
arr

array([100,   2,   3,   4,   5,   6])

In [ ]:
mask = np.logical_and(arr > 3, arr < 6)

In [ ]:
mask # 4 = true ,5= true otherwise false

array([False, False, False,  True,  True, False])

In [ ]:
arr[mask]

array([4, 5])

In [ ]:
#logical or
mask = np.logical_or(arr < 4, arr>5)

In [ ]:
mask

array([ True,  True,  True, False, False,  True])

In [ ]:
arr[mask]

array([100,   2,   3,   6])

# Broadcasting

In [ ]:
img = np.array([[200,250],[100,250]])
img

array([[200, 250],
       [100, 250]])

In [ ]:
brightness = img + 100

In [ ]:
brightness

array([[300, 350],
       [200, 350]])

In [ ]:
img.shape

(2, 2)

In [ ]:
brightness.shape

(2, 2)

In [ ]:
#vectorization
# np.vertorize()------> convert a regular function to be applied on ana array


In [ ]:
def square(x):
  return x*x
vfunc = np.vectorize(square)


In [ ]:
arr

array([100,   2,   3,   4,   5,   6])

In [ ]:
print(vfunc(arr))

[10000     4     9    16    25    36]


#Dealing with missing values
##  np.nan-----> not a number

In [ ]:
a = np.array([1,2,np.nan,4])

In [ ]:
a

array([ 1.,  2., nan,  4.])

In [ ]:
# np.ing  and -np.inf------>possitive and neg infinite values
# np.isnan
# np.isinf
# np.isfinite

#--------> Used to the function to detect null values, infinite values and finite values

In [ ]:
print(np.isnan(a))

[False False  True False]


In [ ]:
print(np.isinf(a))

[False False False False]


In [ ]:
print(np.isfinite(a))

[ True  True False  True]


In [ ]:
b = np.array([1,2,3,np.inf,5])

In [ ]:
print(np.isinf(b))

[False False False  True False]
